apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend-service
  name: frontend-service
spec:
  ports:
  - name: 5000-5000
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30080
  selector:
    app: frontend
  type: NodePort
status:
  loadBalancer: {}
