apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  log.level: debug
  registries.conf: |
    registries:
    - name: Artifactory
      prefix: 192.168.44.44:8082
      api_url: http://192.168.44.44:8082
      insecure: true
      credentials: pullsecret:argocd/regcred